name: Trigger Firmware Flash on Release

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  trigger_flash:
    runs-on: ubuntu-latest

    steps:
    - name: Get Release Info
      id: release_info
      run: |
        echo "::set-output name=download_url::$(curl -s ${{ github.event.release.assets[0].browser_download_url }})"
    
    - name: Trigger Flash on Golden Unit
      env:
        API_URL: ${{ secrets.FLASK_API_URL }}
        API_KEY: ${{ secrets.FLASK_API_KEY }}
      run: |
        curl -X POST "$API_URL/api/trigger-release" \
          -H "Authorization: Bearer $API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "download_url": "${{ steps.release_info.outputs.download_url }}",
            "target": "stm32h723xx"  # specify the correct target
          }'
